version: '2'
services:
  app:
    container_name: app
    build: .
    command: go run main.go
    volumes:
      - ./src:/go/src/app
    working_dir: /go/src/app
    ports:
      - "3030:8000"
    environment:
      PORT: 8000